baseURL = 'https://kohliashish.github.io/'
languageCode = 'en-us'
title = 'Ashish Kohli'


[permalinks]
  blog = "/blog/:slug/"
  posts = "/posts/:year/:month/:day/:slug/"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[taxonomies]
category = "categories"